#!/usr/bin/bash

# oh-my-posh's directory
declare OMP_DIR="${HOME}/.config/oh-my-posh"
# oh-my-posh's themes directory
declare OMP_THEMES_DIR="${OMP_DIR}/themes"


function OhMyPoshSetTheme ()
{
    eval "$(oh-my-posh init bash --config ${OMP_THEMES_DIR}/$1.omp.json)"
}


# nice omp themes:
#   - 1_shell
#   - amro
#   - avit
#   - kali
#   - blue-owl
#   - onehalf.minimal
#   - spaceship
#   - tokyo

OhMyPoshSetTheme "danielectrn"
