# See https://starship.rs/config/


# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false


format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$character"""


[directory]
truncation_length = 1
# truncation_symbol = '…/'
truncation_symbol = ''
style = 'bold green'


[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'bold purple'
symbol = ''
truncation_length = 16
truncation_symbol = '…'


[git_status]
style = 'bold purple'
format = '([$all_status$ahead_behind]($style) )'
conflicted = '='
ahead      = '⇡'
behind     = '⇣'
diverged   = '⇕'
up_to_date = ''
untracked  = '*'
stashed    = '$'
staged     = '+'
modified   = '!'
renamed    = '!'
deleted    = 'x'


[character]
success_symbol            = '[](bold bright-black)' 
error_symbol              = '[](bold red) '
vimcmd_symbol             = '[](bold bright-blue)'
vimcmd_replace_one_symbol = '[](bold bright-yellow)'
vimcmd_replace_symbol     = '[](bold yellow)'
vimcmd_visual_symbol      = '[](bold purple)'
