#!/usr/bin/bash

# echos the directory in which the script is
function scriptdir ()
{
    echo $( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
}


function updatedir ()
{
    # source and destination directory
    declare srcdir=$1
    declare dstdir=$2

    for dir in $srcdir/*
    do

        if [ -d $dir ]
        then
            updatedir $dir $dstdir/$(basename $dir)
        else
            mkdir -p $dstdir
            chmod u+rwx $dstdir

            declare srcfile=$dir
            cp $srcfile $dstdir

            declare dstfile=$dstdir/$(basename $srcfile)
            chmod u+rwx $dstfile
        fi

    done
}



declare -r HERE=$(scriptdir)
updatedir $HERE/.config ~/.config
